#!/usr/bin/env bash

sudo yum -y install java-1.8.0

sudo mkdir /minecraft

sudo chown -R ec2-user:ec2-user /minecraft

cd /minecraft

aws s3 cp s3://<BucketName>/setup/<Enter forge installer jar> /minecraft/<Enter forge installer jar>

java -jar <Enter forge installer jar> --installServer

echo '#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
#Mon Aug 06 18:11:14 UTC 2018
eula=true' > eula.txt

aws s3 cp s3://<BucketName>/setup/mods.zip /minecraft/mods.zip

unzip mods.zip

sudo aws s3 cp s3://<BucketName>/setup/minecraft.service /etc/systemd/system/minecraft.service

sudo systemctl daemon-reload

sudo service minecraft start

sudo yum install screen

screen -S mcserver

java -Xmx1024M -Xms1024M -jar <Forge .jar file> nogui

Here is how to restart the instance after stopping:
1. Start the EC2 instance.
2. Connect to instance.
3. Enter the following in the command line:

cd /minecraft

java -Xmx1024M -Xms1024M -jar minecraft_server.1.12.2.jar nogui

4. Now connect to your minecraft server with the new ip address.
